steps:
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: $(dockerRegistryServiceConnection)
      repository: $(dockerImageName)
      command: buildAndPush
      Dockerfile: '**/Dockerfile'
      tags: |
        $(buildTag)
        latest
